SELECT TOP (1000) [Id]
,[UserName]
,[FirstName]
,[LastName]
,[Email]
,[Password]
,[Gender]
,[DateOfBirth]
,[Address]
,[Role]
,[CreatedUserId]
,[CreatedUserDate]
,[UpdatedUserId]
,[UpdatedUserDate]
FROM [ECommerceDb].[dbo].[Users]